imports:
    - php

filter:
    excluded_paths: [test/*]

tools:
    external_code_coverage: true
before_script:
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    #- phpunit --bootstrap test/config.php test
    - phpunit --bootstrap test/config.php --coverage-clover coverage.clover test

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
